/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadasar;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author GAME
 */
public class formUtama extends javax.swing.JFrame {

    /**
     * Creates new form formUtama
     */
    public formUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuDokter = new javax.swing.JMenuItem();
        MenuObat = new javax.swing.JMenuItem();
        MenuPoliklinik = new javax.swing.JMenuItem();
        MenuCaraBayar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::[ Aplikasi SIMRS ]::");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(214, 26));

        jMenu1.setForeground(new java.awt.Color(0, 100, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/17.png"))); // NOI18N
        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        MenuDokter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MenuDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Doctor.png"))); // NOI18N
        MenuDokter.setText("Dokter");
        MenuDokter.setPreferredSize(new java.awt.Dimension(200, 26));
        MenuDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDokterActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDokter);

        MenuObat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MenuObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Drug-basket-32.png"))); // NOI18N
        MenuObat.setText("Obat");
        MenuObat.setPreferredSize(new java.awt.Dimension(200, 26));
        MenuObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuObatActionPerformed(evt);
            }
        });
        jMenu1.add(MenuObat);

        MenuPoliklinik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MenuPoliklinik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PatientFile.png"))); // NOI18N
        MenuPoliklinik.setText("Poliklinik");
        MenuPoliklinik.setPreferredSize(new java.awt.Dimension(200, 26));
        MenuPoliklinik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPoliklinikActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPoliklinik);

        MenuCaraBayar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MenuCaraBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Money-32x32.png"))); // NOI18N
        MenuCaraBayar.setText("Cara Bayar");
        MenuCaraBayar.setPreferredSize(new java.awt.Dimension(200, 26));
        MenuCaraBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCaraBayarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCaraBayar);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDokterActionPerformed
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        formDokter dokter = new formDokter(this, false);
        dokter.setSize(screen.width - 100, screen.height - 100);
        dokter.setLocationRelativeTo(null);
        dokter.setVisible(true);
    }//GEN-LAST:event_MenuDokterActionPerformed

    private void MenuObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuObatActionPerformed
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        formObat obat = new formObat(this, false);
        obat.setSize(screen.width - 100, screen.height - 100);
        obat.setLocationRelativeTo(null);
        obat.setVisible(true);
    }//GEN-LAST:event_MenuObatActionPerformed

    private void MenuPoliklinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPoliklinikActionPerformed
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        formPoliklinik poliklinik = new formPoliklinik(this, false);
        poliklinik.setSize(screen.width - 100, screen.height - 100);
        poliklinik.setLocationRelativeTo(null);
        poliklinik.setVisible(true);
    }//GEN-LAST:event_MenuPoliklinikActionPerformed

    private void MenuCaraBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCaraBayarActionPerformed
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        formCaraBayar carabayar = new formCaraBayar(this, false);
        carabayar.setSize(screen.width - 100, screen.height - 100);
        carabayar.setLocationRelativeTo(null);
        carabayar.setVisible(true);
    }//GEN-LAST:event_MenuCaraBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCaraBayar;
    private javax.swing.JMenuItem MenuDokter;
    private javax.swing.JMenuItem MenuObat;
    private javax.swing.JMenuItem MenuPoliklinik;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
